---

- name: oraclelinux8
  image: dropveter/oraclelinux8-ansible
- name: almalinux8
  image: dropveter/almalinux8-ansible
- name: ubuntu1804
  image: geerlingguy/docker-ubuntu1804-ansible:latest
- name: ubuntu2004
  image: geerlingguy/docker-ubuntu2004-ansible:latest
