---

- name: Install OpenSCAP packages and requirements
  ansible.builtin.package:
    name: "{{ openscap_packages }}"
    state: present

- name: Distribute script from template
  ansible.builtin.template:
    src: openscap-oval-repost.sh.j2
    dest: /usr/local/bin/openscap-oval-report.sh
    mode: "0700"

- name: Create report directory
  ansible.builtin.file:
    name: "{{ openscap_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"
