---

- name: Ensure no gpg encrypted report exists
  ansible.builtin.file:
    path: "{{ openscap_report }}.gpg"
    state: absent

- name: Encrypt report
  ansible.builtin.command: >-
    gpg --encrypt
        --armor
        --recipient {{ openscap_mail_recipient }}
        --output {{ openscap_report }}.gpg
        {{ openscap_report }}
  changed_when: true
  become: false

- name: Send report via email
  community.general.mail:
    host: "{{ openscap_mail_host | default(omit) }}"
    port: "{{ openscap_mail_port | default(omit) }}"
    username: "{{ openscap_mail_username | default(omit) }}"
    password: "{{ openscap_mail_password | default(omit) }}"
    to: "{{ openscap_mail_recipient }}"
    subject: "OpenSCAP report for {{ ansible_hostname }}"
    attach:
      - "{{ openscap_report }}.gpg"
