---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Perform installation
  ansible.builtin.include_tasks: install.yml

- name: Import GPG key
  ansible.builtin.include_tasks: gpg.yml
  when: openscap_gpg_key is defined

- name: Setup SSH/SFTP connectivity
  ansible.builtin.include_tasks: sftp.yml
  when: openscap_sftp_private_key is defined

- name: Generate OVAL report immediately
  ansible.builtin.include_tasks: report.yml
  when: openscap_immediate | bool

- name: Schedule OVAL report
  ansible.builtin.include_tasks: schedule.yml
  when: openscap_schedule | bool
