---

- name: Load variables based on OS type
  ansible.builtin.include_tasks: vars.yml

- name: Perform installation
  ansible.builtin.include_tasks: install.yml

- name: Schedule OVAL report
  ansible.builtin.include_tasks: schedule.yml
  when: openscap_schedule | bool

- name: Execute and retrieve output
  ansible.builtin.include_tasks: execute.yml
  when: openscap_immediate | bool

