---

# - name: Define varaibles to make it code better readable
#   set_fact:
#     openscap_archive: "{{ openscap_tmp_dir }}/{{ openscap_url | basename }}"
#     openscap_file: "{{ openscap_tmp_dir }}/{{ openscap_url | basename | regex_replace('\\.bz2') }}"
#     openscap_report: "{{ openscap_tmp_dir }}/oval-report-{{ inventory_hostname }}.html"

- name: Delete previous files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ openscap_archive }}"
    - "{{ openscap_file }}"
    - "{{ openscap_report }}"
    - "{{ openscap_report }}.gpg"

- name: Download latest OpenSCAP file
  ansible.builtin.get_url:
    url: "{{ openscap_url }}"
    dest: "{{ openscap_archive }}"
    mode: "0600"

- name: Unpack the archive
  ansible.builtin.command: bzip2 -d {{ openscap_archive }}
  changed_when: true
  args:
    chdir: "{{ openscap_tmp_dir }}"
  when: openscap_archive is search('\.bz2')

- name: Execute OpenSCAP
  ansible.builtin.command: oscap oval eval --report {{ openscap_report }} {{ openscap_file }}
  changed_when: true
  args:
    chdir: "{{ openscap_tmp_dir }}"

- name: Retrieve report
  ansible.builtin.fetch:
    src: "{{ openscap_report }}"
    dest: /tmp/
    flat: yes

- name: Delete oval files & report
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ openscap_archive }}"
    - "{{ openscap_file }}"
    - "{{ openscap_report }}"
