---

- name: Delete previous files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ openscap_archive }}"
    - "{{ openscap_file }}"
    - "{{ openscap_report }}"
    - "{{ openscap_report }}.gpg"

- name: Download latest OpenSCAP file
  ansible.builtin.get_url:
    url: "{{ openscap_url }}"
    dest: "{{ openscap_archive }}"
    mode: "0600"

- name: Unpack the archive
  ansible.builtin.command: bzip2 -d {{ openscap_archive }}
  changed_when: true
  args:
    chdir: "{{ openscap_log_dir }}"
  when: openscap_archive is search('\.bz2')

- name: Execute OpenSCAP
  ansible.builtin.command: oscap oval eval --report {{ openscap_report }} {{ openscap_file }}
  changed_when: true
  args:
    chdir: "{{ openscap_log_dir }}"

- name: Create local path
  ansible.builtin.file:
    path: "{{ openscap_central_report_path }}/{{ inventory_hostname }}"
    state: directory
    mode: "0750"

- name: Retrieve report
  ansible.builtin.fetch:
    src: "{{ openscap_report }}"
    dest: "{{ openscap_central_report_path }}/{{ inventory_hostname }}/"
    flat: yes

- name: Delete oval files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ openscap_archive }}"
    - "{{ openscap_file }}"
