---

- name: Create HTML report for all hosts
  run_once: yes
  become: "{{ 'no' if openscap_central_server == 'localhost' else 'yes' }}"
  delegate_to: "{{ openscap_central_server }}"
  block:

    - name: Get all SSG reports
      ansible.builtin.find:
        paths: "{{ openscap_central_report_path }}"
        patterns: "xccdf-report.html"
        recurse: yes
      register: __reports

    - name: Read results
      ansible.builtin.command: >-
        cat "{{ openscap_central_report_ssg }}"
      register: x
      changed_when: false

    - name: Import results
      ansible.builtin.set_fact:
        openscap_results: "{{ x.stdout | from_yaml }}"

    - name: Create HTML report from template
      ansible.builtin.template:
        src: templates/table-ssg.html.j2
        dest: "{{ openscap_central_report_path }}/index-ssg.html"
        mode: "0644"
