---

- name: Delete previous files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ openscap_archive }}"
    - "{{ openscap_file }}"
    - "{{ openscap_report }}"
    - "{{ openscap_report }}.gpg"

- name: Execute the openscap script
  ansible.builtin.command: >-
    {{ openscap_schedule_command }}
  changed_when: true

- name: Create local path
  ansible.builtin.file:
    path: "{{ openscap_central_report_path }}/{{ inventory_hostname }}"
    state: directory
    owner: "{{ lookup('pipe', 'id -un') }}"
    group: "{{ lookup('pipe', 'id -gn') }}"
    mode: "0750"
  run_once: yes
  become: yes
  delegate_to: localhost

- name: Get all remote files
  ansible.builtin.find:
    paths: "{{ openscap_log_dir }}"
  register: __find

- name: Retrieve report
  ansible.builtin.fetch:
    src: "{{ file.path }}"
    dest: "{{ openscap_central_report_path }}/{{ inventory_hostname }}/"
    flat: yes
  loop: "{{ __find.files }}"
  loop_control:
    loop_var: file
    label:
      - "{{ file.path }}"

- name: Delete oval files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ openscap_archive }}"
    - "{{ openscap_file }}"
