---

- name: Ensure all components are present
  ansible.builtin.include_role:
    name: deitkrachten.cron

- name: Schedule daily report
  ansible.builtin.cron:
    name: OpenSCAP OVAL report
    weekday: "{{ openscap_schedule_times['weekday'] }}"
    minute: "{{ openscap_schedule_times['minute'] }}"
    hour: "{{ openscap_schedule_times['hour'] }}"
    user: root
    job: "{{ openscap_schedule_command }}"
    cron_file: openscap-oval-report
