---

- name: Ensure all components are present
  ansible.builtin.include_role:
    name: deitkrachten.cron

- name: Schedule daily report
  ansible.builtin.cron:
    name: OpenSCAP OVAL report
    weekday: "{{ openscap_schedule_times['weekday'] }}"
    minute: "{{ openscap_schedule_times['minute'] }}"
    hour: "{{ openscap_schedule_times['hour'] }}"
    user: root
    job: /usr/local/bin/openscap-oval-report.sh
    cron_file: openscap-oval-report

- name: Execute scheduled script immediately
  when: openscap_immediate | bool
  tags: molecule-idempotence-notest
  block:

    - name: Execute script
      ansible.builtin.command:
        cmd: /usr/local/bin/openscap-oval-report.sh
      changed_when: true
      register: __openscap_script

    - name: Show output
      ansible.builtin.debug:
        var: __openscap_script

