---

- name: Converge
  hosts: all
  become: "yes"
  vars:
    openscap_gpg_recipient: foo@example.com
    openscap_gpg_key: "{{ lookup('file', 'files/foo.pub') }}"
  tasks:
    - name: Include role 'ansible-role-openscap'
      ansible.builtin.include_role:
        name: ansible-role-openscap
