---

- name: Converge
  hosts: all
  become: "False"
  vars:
    openscap_central_download: True
    openscap_central_collection: True
    openscap_central_path: /tmp/report
    openscap_central_report_path: /tmp/report
    openscap_central_mode: "0644"
    openscap_oval_immediate: True
    openscap_ssg_immediate: True
  tasks:
    - name: Include role 'ansible-role-openscap'
      ansible.builtin.include_role:
        name: ansible-role-openscap
